apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: my-container-2
      image: nginx
      ports:
        - containerPort: 80
